### ISSUE TITLE
Unable to install from apt-get

### ISSUE THREAD

**Issue by sangwoo-joh** [Parrot-Developers/ulog#1]
Hi.
I'm trying to install your [parrot-sphinx](https://developer.parrot.com/docs/sphinx/installation.html#add-new-apt-repository-to-your-system).

However, when I tried to install using `apt-get install parrot-sphinx`, it says:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 parrot-sphinx : Conflicts: ulogger-dkms
E: Unable to correct problems, you have held broken packages.
```

I think there is some dependency issue with this project.

**Comment by slekieffre** [comment]
Hi,
This is a known problem, specific to ubuntu 18.04.
It will be fixed in the next release, which should be ready within shortly.

**Comment by sangwoo-joh** [comment]
Thanks. Looking forward to the next release!
