### ISSUE TITLE
ulogger-dkms: installation crashes

### ISSUE THREAD

**Issue by lv-alerion** [Parrot-Developers/ulog#7]
Hi,

I am trying to install parrot-sphinx  on Ubuntu 22.04, kernel 6.5.0-14-generic.

There is an issue when installing `ulogger-dkms`:

```
/var/lib/dkms/ulogger/1.13/build/ulogger-6.x.c: In function 'ulogger_write_iter':
/var/lib/dkms/ulogger/1.13/build/ulogger-6.x.c:639:44: error: implicit declaration of function 'iov_iter_iovec'; did you man 'iov_iter_bvec'? [-Werror=implicit-function-declaration]
```

Should I find a way to compile without the option `implicit-function-declaration` or is the problem fixable on your side ?

Thanks !

**Comment by ymorgan** [comment]
Hi, thanks for the report.

We updated the package on debian.parrot.com that should fix the build issue. It should be visible soon (depending on caches) via an apt update (ulogger-dkms version 1.15)

YMM

**Comment by lv-alerion** [comment]
Hi,

thanks for your prompt update, I can confirm that installation is now going smoothly.
